# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Tech Brew
tagline:          'Linux hacks, python hacks, living in the cloud'
description:      'Linux hacks, python hacks, living in the cloud'
url:              http://hyde.getpoole.com
baseurl:          http://jasonrhaas.github.io/hyde/
# baseurl: /

author:
  name:           'Jason Haas'
  url:            https://twitter.com/jasonrhaas

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/jasonrhaas
